### ISSUE TITLE
CRASH at buildozer permission

### ISSUE THREAD

**Issue by sooko** [b3b/able#37] opened 2022-12-23 22:04 UTC
App crashed on android 12  api 31  when declare android permision BLUETTOH and BLUETOOTH_ADMIN.

**Comment by b3b** [comment] 2023-01-01 22:38
Thank you for reporting this issue, @sooko 
Fixed in `able 1.0.12` .
To build with the new version, additional permissions should be added to `buildozer.spec`:

```
android.permissions =
    BLUETOOTH,
    BLUETOOTH_ADMIN,
    BLUETOOTH_SCAN,
    BLUETOOTH_CONNECT,
    BLUETOOTH_ADVERTISE,
    ACCESS_FINE_LOCATION
```

Since Android 12, new runtime permissions are required:
- `BLUETOOTH_CONNECT` - allow to connecto to devices, and turn on the Bluetooth adapter
 - `BLUETOOTH_SCAN` - allow to start the scan
- `BLUETOOTH_ADVERTISE` - allow to advertise

Crash was caused by attempt to to turn on the adapter without obtaining `BLUETOOTH_CONNECT` permission first.

In new `able` version, permissions are requested before before trying to access the adapter.

**Closed** 2023-01-02 08:14 UTC
Labels: bug
